-- Table for information about users
create table _user(
    id int generated by default as identity primary key,
    created_date date,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    middle_name varchar(50),
    login varchar(30) not null unique,
    email varchar(50) not null unique
);

-- Information about User authorities
create table user_auth(
    id int generated by default as identity primary key,
    user_id int references _user(id) on delete cascade,
    password_hash varchar not null,
    status varchar(50),
    deleted boolean not null
);

--  Roles in system
create table role(
    id int generated by default as identity primary key,
    code varchar(50) not null,
    created_date date,
    deleted boolean
);

-- Information about User roles
 create table user_role(
     id int generated by default as identity primary key,
     user_id int references _user(id),
     role_id int references role(id),
     created_date date,
     active boolean,
     deleted boolean
);

-- Information about product categories
create table category(
    id int generated by default as identity primary key,
    category_code varchar(50) not null,
    description text,
    deleted boolean
);

-- Information about products
create table product(
    id int generated by default as identity primary key,
    product_name varchar(100) not null,
    category_id int references category(id),
    price double precision not null,
    description text not null,
    deleted boolean
);