-- Table for information about users
CREATE TABLE _user (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(50) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       middle_name VARCHAR(50),
                       login VARCHAR(30) NOT NULL UNIQUE,
                       email VARCHAR(50) NOT NULL UNIQUE,
                       created_date TIMESTAMP
);

-- Information about User authorities
CREATE TABLE user_auth (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id INT REFERENCES _user(id) ON DELETE CASCADE,
                           password_hash VARCHAR NOT NULL,
                           status VARCHAR(50),
                           deleted BOOLEAN DEFAULT FALSE,
                           created_date TIMESTAMP
);

-- Roles in the system
CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR(50) NOT NULL,
                      deleted BOOLEAN DEFAULT FALSE,
                      created_date TIMESTAMP
);

-- Information about User roles
CREATE TABLE user_role (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id INT REFERENCES _user(id),
                           role_id INT REFERENCES role(id),
                           active BOOLEAN,
                           deleted BOOLEAN DEFAULT FALSE,
                           created_date TIMESTAMP
);

-- Information about product categories
CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_code VARCHAR(50) NOT NULL,
                          description TEXT,
                          deleted BOOLEAN DEFAULT FALSE,
                          created_date TIMESTAMP
);

-- Inventory table
CREATE TABLE inventory (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           quantity VARCHAR(50) NOT NULL,
                           description TEXT,
                           deleted BOOLEAN DEFAULT FALSE,
                           created_date TIMESTAMP
);

-- Information about products
CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         product_name VARCHAR(100) NOT NULL,
                         category_id INT REFERENCES category(id),
                         inventory_id INT REFERENCES inventory(id),
                         price INT NOT NULL CHECK (price > 0),
                         description TEXT NOT NULL,
                         deleted BOOLEAN DEFAULT FALSE,
                         created_date TIMESTAMP
);

-- User payment information
CREATE TABLE user_payment (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id INT REFERENCES _user(id),
                              payment_type VARCHAR(255),
                              provider VARCHAR(255),
                              account_no VARCHAR(255),
                              expiry DATE NOT NULL,
                              deleted BOOLEAN DEFAULT FALSE,
                              created_date TIMESTAMP
);

-- Payment status table
CREATE TABLE payment_status (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255),
                                deleted BOOLEAN DEFAULT FALSE,
                                created_date TIMESTAMP
);

-- Cart items table
CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id INT REFERENCES _user(id),
                           product_id INT REFERENCES product(id),
                           quantity INT,
                           total_price INT NOT NULL CHECK (total_price > 0),
                           deleted BOOLEAN DEFAULT FALSE,
                           created_date TIMESTAMP
);

-- Order details table
CREATE TABLE order_details (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id INT REFERENCES _user(id),
                               product_id INT REFERENCES product(id),
                               quantity INT,
                               total_price INT NOT NULL CHECK (total_price > 0),
                               deleted BOOLEAN DEFAULT FALSE,
                               created_date TIMESTAMP
);


-- Payment details table
CREATE TABLE payment_details (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 order_id INT REFERENCES order_details(id),
                                 payment_id INT REFERENCES user_payment(id),
                                 status_id INT REFERENCES payment_status(id),
                                 deleted BOOLEAN DEFAULT FALSE,
                                 created_date TIMESTAMP
);
